mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
# Domain Aliases
  type-aliases-package: com.example.demo.entity
# JDBC null settings
  configuration:
    jdbc-type-for-null: null

server:
  port: 8000

spring:
  security:
    user:
      name: root
      password: root123
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bootex
    username: root
    password: root123


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json